# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: windows-2019

steps:

- script: |
    git checkout v1.3.x
  displayName: 'git checkout'

- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '6.17.1'
  displayName: 'Install Node.js'

- task: UsePythonVersion@0
  inputs:
    versionSpec: '2.7.18'
    addToPath: true
    architecture: 'x64'

- script: |
    npm install -g bower@1.3.9
  displayName: 'npm install bower'

- script: |
    npm install -g grunt-cli@v1.2.0
  displayName: 'npm install grunt'

- script: |
    node --version
  displayName: 'npm install bower'

- script: |
    python --version
  displayName: 'npm install bower'


- script: |
    npm cache clean -f
  displayName: 'npm install bower'

- script: |
    rm -rf node_modules
  displayName: 'npm install bower'
  

- script: |
    npm install
  displayName: 'npm install and build'
